events {
    worker_connections 1024;
}

http {
    upstream web-app {
        # Docker internal DNS automatically round-robins requests to all replicas of the web-app service
        server web-app:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://web-app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeout configurations
            proxy_connect_timeout 5s;
            proxy_read_timeout 15s;
            proxy_send_timeout 15s;
        }
    }
}
